name: 'Dependency Review'

on: 
  workflow_dispatch:
  push:
    paths:
      - "package.json"

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          base-ref: refs/heads/main~1
          head-ref: refs/heads/main
